/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 상태 변경 요청용 CSRF 토큰 발급 */
        get: operations["getCsrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/local/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로컬 계정 회원가입
         * @description 아이디와 전화번호는 중복될 수 없으며 비밀번호는 BCrypt 해시로만 저장한다.
         */
        post: operations["registerLocalMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/local/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로컬 계정 로그인
         * @description 로그인에 성공하면 카카오 로그인과 같은 서버 세션을 생성하고 다음 화면 경로를 반환한다.
         */
        post: operations["loginLocalMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 현재 사용자 조회 */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 최초 온보딩 완료 */
        patch: operations["completeOnboarding"];
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 내 프로필 수정 */
        patch: operations["updateMyProfile"];
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 게시 행사 목록 조회 */
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 행사 상세 조회 */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/participation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 행사 참가 신청 */
        post: operations["joinEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/participation/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 행사 참가 취소 */
        post: operations["cancelEventParticipation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/payment-obligations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 납부 항목 목록 */
        get: operations["getMyPaymentObligations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment-obligations/{paymentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 납부 상세 조회 */
        get: operations["getPaymentObligation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment-obligations/{paymentId}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 송금 완료 신고 */
        post: operations["reportPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 운영진 대시보드 조회 */
        get: operations["getAdminDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 알림 목록과 읽지 않은 개수 조회 */
        get: operations["getNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 알림 읽음 처리 */
        post: operations["readNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 모든 알림 읽음 처리 */
        post: operations["readAllNotifications"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 운영진 행사 전체 목록 조회 */
        get: operations["getAdminEvents"];
        put?: never;
        /** 행사 초안 생성 */
        post: operations["createAdminEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 운영진 행사 상세 조회 */
        get: operations["getAdminEvent"];
        put?: never;
        post?: never;
        /** 참가 이력이 없는 행사 초안 삭제 */
        delete: operations["deleteAdminEvent"];
        options?: never;
        head?: never;
        /** 행사 초안 수정 */
        patch: operations["updateAdminEvent"];
        trace?: never;
    };
    "/admin/events/{eventId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 행사 초안 공개 */
        post: operations["publishAdminEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/events/{eventId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 공개 행사 종료 */
        post: operations["closeAdminEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/events/{eventId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 행사 취소 및 납부 상태 정리 */
        post: operations["cancelAdminEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/events/{eventId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 행사별 참가자와 참가비 납부 현황 조회 */
        get: operations["getAdminEventParticipants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dues-rounds/{duesRoundId}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 회비 차수별 부원 납부 현황 조회 */
        get: operations["getAdminDuesPayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dues-rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 회비 차수 목록 조회 */
        get: operations["getAdminDuesRounds"];
        put?: never;
        /** 회비 차수 초안 생성 */
        post: operations["createAdminDuesRound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dues-rounds/{duesRoundId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 회비 차수 초안 삭제 */
        delete: operations["deleteAdminDuesRound"];
        options?: never;
        head?: never;
        /** 회비 차수 초안 수정 */
        patch: operations["updateAdminDuesRound"];
        trace?: never;
    };
    "/admin/dues-rounds/{duesRoundId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 회비 차수 공개 및 활성 부원 납부 항목 생성 */
        post: operations["publishAdminDuesRound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payment-obligations/{paymentId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 송금 신고 승인 */
        post: operations["confirmAdminPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payment-obligations/{paymentId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 송금 신고 반려 */
        post: operations["rejectAdminPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/refunds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 환불 대기 목록 조회 */
        get: operations["getAdminRefunds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payment-obligations/{paymentId}/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 환불 완료 처리 */
        post: operations["completeAdminRefund"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 회원 목록 조회 */
        get: operations["getAdminMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/{memberId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 가입 대기 회원 승인 */
        post: operations["approveAdminMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/{memberId}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 활성 회원 정지 */
        post: operations["suspendAdminMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/{memberId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 활성 회원 역할 변경 */
        patch: operations["changeAdminMemberRole"];
        trace?: never;
    };
    "/admin/payment-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 송금정보 버전 목록 */
        get: operations["getAdminPaymentSettings"];
        put?: never;
        /** 새 송금정보 등록 및 활성화 */
        post: operations["createAdminPaymentSetting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payment-settings/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 현재 활성 송금정보 조회 */
        get: operations["getActiveAdminPaymentSetting"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CsrfResponse: {
            headerName: string;
            parameterName: string;
            token: string;
        };
        LocalRegisterRequest: {
            /** @example dclub.member */
            loginId: string;
            /**
             * Format: password
             * @example clubpass123!
             */
            password: string;
            /** @example 010-1234-5678 */
            phoneNumber: string;
        };
        LocalRegisterResponse: {
            /** Format: int64 */
            memberId: number;
            loginId: string;
        };
        LocalLoginRequest: {
            /** @example dclub.member */
            loginId: string;
            /**
             * Format: password
             * @example clubpass123!
             */
            password: string;
        };
        LocalLoginResponse: {
            member: components["schemas"]["MeResponse"];
            /** @enum {string} */
            redirectPath: "/onboarding" | "/pending" | "/home";
        };
        /** @enum {string} */
        MemberPart: "PLAN" | "DESIGN" | "PE_WEB" | "PE_MOBILE";
        /** @enum {string} */
        MemberRole: "MEMBER" | "STAFF" | "ADMIN";
        /** @enum {string} */
        MemberStatus: "PENDING" | "ACTIVE" | "SUSPENDED" | "WITHDRAWN";
        /** @enum {string} */
        EventStatus: "DRAFT" | "PUBLISHED" | "CLOSED" | "CANCELED";
        /** @enum {string} */
        ParticipationStatus: "JOINED" | "CANCELED";
        /** @enum {string} */
        PaymentType: "EVENT_FEE" | "MEMBERSHIP_DUE";
        /** @enum {string} */
        PaymentStatus: "NOT_REQUIRED" | "UNPAID" | "REPORTED" | "CONFIRMED" | "REJECTED" | "VOID" | "REFUND_PENDING" | "REFUNDED";
        /** @enum {string} */
        PaymentMethod: "BANK_TRANSFER" | "KAKAO_PAY_CODE";
        MeResponse: {
            /** Format: int64 */
            id: number;
            kakaoProfileName?: string;
            loginId?: string;
            name?: string;
            part?: components["schemas"]["MemberPart"];
            displayNickname?: string;
            role: components["schemas"]["MemberRole"];
            status: components["schemas"]["MemberStatus"];
            onboardingCompleted: boolean;
            /** Format: date-time */
            approvedAt?: string;
        };
        OnboardingRequest: {
            name: string;
            part: components["schemas"]["MemberPart"];
        };
        EventListItem: {
            /** Format: int64 */
            id: number;
            title: string;
            summary?: string;
            location?: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt?: string;
            /** Format: date-time */
            registrationDeadline: string;
            capacity?: number;
            joinedCount: number;
            /** Format: int64 */
            feeAmount: number;
            status: components["schemas"]["EventStatus"];
            myParticipationStatus?: components["schemas"]["ParticipationStatus"];
            myPaymentStatus?: components["schemas"]["PaymentStatus"];
        };
        EventPage: {
            items: components["schemas"]["EventListItem"][];
            page: number;
            size: number;
            totalElements: number;
            totalPages: number;
        };
        ParticipationSummary: {
            /** Format: int64 */
            id: number;
            status: components["schemas"]["ParticipationStatus"];
            /** Format: date-time */
            joinedAt: string;
            /** Format: date-time */
            canceledAt?: string;
            /** Format: int64 */
            version: number;
        };
        PaymentSummary: {
            /** Format: int64 */
            id: number;
            type: components["schemas"]["PaymentType"];
            /** Format: int64 */
            amount: number;
            status: components["schemas"]["PaymentStatus"];
            /** Format: date-time */
            dueAt?: string;
            source: components["schemas"]["PaymentSource"];
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
        };
        PaymentSource: {
            /** @enum {string} */
            type: "EVENT" | "DUES_ROUND";
            /** Format: int64 */
            id: number;
            title: string;
            /** Format: date-time */
            dueAt?: string;
        };
        EventDetail: components["schemas"]["EventListItem"] & {
            description: string;
            allowLateCancellation: boolean;
            canJoin: boolean;
            canCancel: boolean;
            myParticipation?: components["schemas"]["ParticipationSummary"];
            myPayment?: components["schemas"]["PaymentSummary"];
        };
        JoinEventResponse: {
            participation: components["schemas"]["ParticipationSummary"];
            payment: components["schemas"]["PaymentSummary"];
        };
        CancelParticipationRequest: {
            /** Format: int64 */
            version: number;
            reason?: string;
        };
        CancelParticipationResponse: {
            participationStatus: components["schemas"]["ParticipationStatus"];
            paymentStatus: components["schemas"]["PaymentStatus"];
            refundRequired: boolean;
        };
        PaymentPage: {
            items: components["schemas"]["PaymentSummary"][];
            page: number;
            size: number;
            totalElements: number;
            totalPages: number;
        };
        PaymentDestination: {
            bankName: string;
            accountNumber: string;
            accountHolder: string;
            /** Format: uri */
            kakaoPayReceiveUrl?: string;
        };
        PaymentReport: {
            /** Format: int64 */
            id: number;
            method: components["schemas"]["PaymentMethod"];
            senderName: string;
            /** Format: date-time */
            transferredAt?: string;
            note?: string;
            /** Format: date-time */
            reportedAt: string;
        };
        PaymentStatusHistory: {
            fromStatus?: components["schemas"]["PaymentStatus"];
            toStatus: components["schemas"]["PaymentStatus"];
            reason?: string;
            /** Format: date-time */
            changedAt: string;
        };
        PaymentDetail: components["schemas"]["PaymentSummary"] & {
            paymentDestination?: components["schemas"]["PaymentDestination"];
            latestReport?: components["schemas"]["PaymentReport"];
            statusHistory: components["schemas"]["PaymentStatusHistory"][];
        };
        PaymentReportRequest: {
            method: components["schemas"]["PaymentMethod"];
            senderName: string;
            /** Format: date-time */
            transferredAt?: string;
            note?: string;
            /** @constant */
            transferConfirmed: true;
            /** Format: int64 */
            version: number;
        };
        PaymentReportResponse: {
            report: components["schemas"]["PaymentReport"];
            paymentStatus: components["schemas"]["PaymentStatus"];
            /** Format: int64 */
            version: number;
        };
        AdminEventCreateRequest: {
            title: string;
            summary?: string;
            description: string;
            location?: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt?: string;
            /** Format: date-time */
            registrationDeadline: string;
            capacity?: number;
            /** Format: int64 */
            feeAmount: number;
            allowLateCancellation: boolean;
        };
        AdminEventUpdateRequest: components["schemas"]["AdminEventCreateRequest"] & {
            /** Format: int64 */
            version: number;
        };
        AdminEventVersionRequest: {
            /** Format: int64 */
            version: number;
        };
        AdminEventTransitionRequest: {
            /** Format: int64 */
            version: number;
            reason?: string;
        };
        AdminEventCancelResponse: {
            eventStatus: components["schemas"]["EventStatus"];
            /** Format: int64 */
            voidedPaymentCount: number;
            /** Format: int64 */
            refundPendingCount: number;
            /** Format: int64 */
            version: number;
        };
        AdminEventResponse: {
            /** Format: int64 */
            id: number;
            title: string;
            summary?: string;
            description: string;
            location?: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt?: string;
            /** Format: date-time */
            registrationDeadline: string;
            capacity?: number;
            /** Format: int64 */
            joinedCount: number;
            /** Format: int64 */
            feeAmount: number;
            status: components["schemas"]["EventStatus"];
            allowLateCancellation: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
        };
        AdminDashboardResponse: {
            memberCount: number;
            pendingMemberCount: number;
            upcomingEventCount: number;
            unpaidCount: number;
            reportedCount: number;
            /** Format: int64 */
            expectedAmount: number;
            /** Format: int64 */
            confirmedAmount: number;
            /** Format: double */
            collectionRate: number;
            upcomingEvents: components["schemas"]["AdminEventSummary"][];
            activeDuesRounds: components["schemas"]["AdminDuesRoundSummary"][];
            recentReports: components["schemas"]["AdminPaymentRow"][];
        };
        AdminEventSummary: {
            /** Format: int64 */
            id: number;
            title: string;
            /** Format: date-time */
            startsAt: string;
            capacity?: number;
            joinedCount: number;
            /** Format: int64 */
            feeAmount: number;
            unpaidCount: number;
            reportedCount: number;
            confirmedCount: number;
        };
        AdminDuesRoundSummary: {
            /** Format: int64 */
            id: number;
            title: string;
            /** Format: int64 */
            amount: number;
            /** Format: date-time */
            dueAt: string;
            targetCount: number;
            unpaidCount: number;
            reportedCount: number;
            confirmedCount: number;
            /** Format: int64 */
            confirmedAmount: number;
        };
        /** @enum {string} */
        AdminDuesRoundStatus: "DRAFT" | "PUBLISHED" | "CLOSED";
        AdminDuesRoundRequest: {
            title: string;
            /** Format: int64 */
            amount: number;
            /** Format: date-time */
            dueAt: string;
            bankName?: string;
            accountNumber?: string;
            accountHolder?: string;
            kakaoPayReceiveUrl?: string;
            /** Format: int64 */
            version: number;
        };
        AdminDuesRoundResponse: {
            /** Format: int64 */
            id: number;
            title: string;
            /** Format: int64 */
            amount: number;
            /** Format: date-time */
            dueAt: string;
            status: components["schemas"]["AdminDuesRoundStatus"];
            bankName?: string;
            accountNumber?: string;
            accountHolder?: string;
            kakaoPayReceiveUrl?: string;
            /** Format: int64 */
            targetCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
        };
        AdminDuesPublishResponse: {
            duesRound: components["schemas"]["AdminDuesRoundResponse"];
            /** Format: int64 */
            createdPaymentCount: number;
        };
        AdminPaymentRow: {
            /** Format: int64 */
            paymentId: number;
            /** Format: int64 */
            memberId: number;
            nickname: string;
            name: string;
            part: components["schemas"]["MemberPart"];
            /** Format: int64 */
            amount: number;
            status: components["schemas"]["PaymentStatus"];
            /** Format: date-time */
            dueAt: string;
            latestReport?: components["schemas"]["PaymentReport"];
            /** Format: int64 */
            version: number;
        };
        AdminEventParticipant: {
            /** Format: int64 */
            participationId: number;
            /** Format: int64 */
            memberId: number;
            nickname: string;
            name: string;
            part: components["schemas"]["MemberPart"];
            /** Format: date-time */
            joinedAt: string;
            /** Format: int64 */
            paymentId?: number;
            /** Format: int64 */
            amount: number;
            paymentStatus: components["schemas"]["PaymentStatus"];
            latestReport?: components["schemas"]["PaymentReport"];
            /** Format: int64 */
            version: number;
        };
        AdminEventParticipantPage: {
            event: components["schemas"]["AdminEventSummary"];
            items: components["schemas"]["AdminEventParticipant"][];
            page: number;
            size: number;
            totalElements: number;
            totalPages: number;
        };
        AdminDuesPaymentPage: {
            duesRound: components["schemas"]["AdminDuesRoundSummary"];
            items: components["schemas"]["AdminPaymentRow"][];
            page: number;
            size: number;
            totalElements: number;
            totalPages: number;
        };
        AdminPaymentReviewRequest: {
            /** Format: int64 */
            version: number;
            note?: string;
        };
        AdminPaymentReviewResponse: {
            /** Format: int64 */
            paymentId: number;
            status: components["schemas"]["PaymentStatus"];
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            reviewedAt: string;
        };
        AdminMemberResponse: {
            /** Format: int64 */
            id: number;
            kakaoProfileName?: string;
            loginId?: string;
            name?: string;
            part?: components["schemas"]["MemberPart"];
            displayNickname?: string;
            role: components["schemas"]["MemberRole"];
            status: components["schemas"]["MemberStatus"];
            onboardingCompleted: boolean;
            /** Format: date-time */
            approvedAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
        };
        AdminMemberActionRequest: {
            /** Format: int64 */
            version: number;
        };
        AdminMemberRoleRequest: {
            role: components["schemas"]["MemberRole"];
            /** Format: int64 */
            version: number;
        };
        PaymentSettingRequest: {
            bankName: string;
            accountNumber: string;
            accountHolder: string;
            kakaoPayReceiveUrl?: string;
        };
        PaymentSettingResponse: {
            /** Format: int64 */
            id: number;
            bankName: string;
            accountNumber: string;
            accountHolder: string;
            kakaoPayReceiveUrl?: string;
            active: boolean;
            /** Format: int64 */
            createdBy: number;
            /** Format: date-time */
            createdAt: string;
        };
        NotificationItem: {
            /** Format: int64 */
            id: number;
            title: string;
            body: string;
            linkUrl?: string;
            /** Format: date-time */
            readAt?: string;
            /** Format: date-time */
            createdAt: string;
        };
        NotificationResponse: {
            items: components["schemas"]["NotificationItem"][];
            /** Format: int64 */
            unreadCount: number;
        };
        /** @description 모든 API 실패에 사용하는 RFC 7807 호환 공통 응답 */
        Problem: {
            /**
             * @description 오류 유형 URI. 별도 문서 URI가 없으면 about:blank
             * @example about:blank
             */
            type: string;
            /**
             * @description HTTP 상태 이름
             * @example Bad Request
             */
            title: string;
            /**
             * @description HTTP 상태 코드
             * @example 400
             */
            status: number;
            /**
             * @description 프론트엔드 분기 처리용 안정적인 오류 코드
             * @example VALIDATION_FAILED
             */
            code: string;
            /**
             * @description 사용자에게 표시할 수 있는 오류 설명
             * @example 요청 값을 확인해 주세요.
             */
            detail: string;
            /**
             * @description 오류가 발생한 요청 경로
             * @example /api/v1/me/onboarding
             */
            instance: string;
            /**
             * Format: date-time
             * @description 오류 발생 시각(UTC)
             */
            timestamp: string;
            /** @description 필드 단위 검증 오류. 검증 오류가 아니면 빈 배열 */
            fieldErrors: {
                /**
                 * @description 오류 필드명
                 * @example name
                 */
                field: string;
                /**
                 * @description 검증 실패 이유
                 * @example 공백일 수 없습니다
                 */
                reason: string;
            }[];
        };
    };
    responses: {
        /** @description 요청 본문·경로·쿼리 값 오류 (`VALIDATION_FAILED`, `MALFORMED_JSON`, `INVALID_REQUEST`) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 로그인 세션 없음·만료 또는 로컬 계정 정보 불일치 (`AUTHENTICATION_REQUIRED`, `INVALID_CREDENTIALS`) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 역할·소유권 부족 또는 CSRF 토큰 오류 (`FORBIDDEN`, `CSRF_TOKEN_INVALID`) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 리소스가 없거나 현재 사용자에게 비공개 (`RESOURCE_NOT_FOUND`) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 도메인 상태·낙관적 잠금 충돌 (`CONCURRENT_UPDATE` 또는 도메인별 `*_CONFLICT`) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 지원하지 않는 HTTP 메서드 (`METHOD_NOT_ALLOWED`) */
        MethodNotAllowed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 예상하지 못한 서버 오류 (`INTERNAL_SERVER_ERROR`). 내부 예외 상세는 노출하지 않는다. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        EventId: number;
        PaymentId: number;
        DuesRoundId: number;
        MemberId: number;
        NotificationId: number;
        Page: number;
        Size: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCsrfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF 토큰 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
        };
    };
    registerLocalMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalRegisterRequest"];
            };
        };
        responses: {
            /** @description 가입된 로컬 계정 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalRegisterResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    loginLocalMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalLoginRequest"];
            };
        };
        responses: {
            /** @description 로그인한 회원과 다음 화면 경로 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalLoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 현재 사용자 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    completeOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingRequest"];
            };
        };
        responses: {
            /** @description 온보딩 완료 사용자 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingRequest"];
            };
        };
        responses: {
            /** @description 수정된 사용자 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getEvents: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
                participating?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 행사 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 행사 상세 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    joinEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 참가 신청 결과 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinEventResponse"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    cancelEventParticipation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelParticipationRequest"];
            };
        };
        responses: {
            /** @description 참가 취소 결과 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelParticipationResponse"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    getMyPaymentObligations: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
                status?: components["schemas"]["PaymentStatus"][];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 납부 항목 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentPage"];
                };
            };
        };
    };
    getPaymentObligation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: components["parameters"]["PaymentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 납부 상세 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    reportPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: components["parameters"]["PaymentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentReportRequest"];
            };
        };
        responses: {
            /** @description 접수된 송금 신고 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentReportResponse"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    getAdminDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 운영 현황 요약 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDashboardResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 내 알림 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponse"];
                };
            };
        };
    };
    readNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: components["parameters"]["NotificationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 읽은 알림 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationItem"];
                };
            };
        };
    };
    readAllNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 처리 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAdminEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 행사 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventResponse"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createAdminEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminEventCreateRequest"];
            };
        };
        responses: {
            /** @description 생성된 행사 초안 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAdminEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 행사 상세 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteAdminEvent: {
        parameters: {
            query: {
                version: number;
            };
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    updateAdminEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminEventUpdateRequest"];
            };
        };
        responses: {
            /** @description 수정된 행사 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventResponse"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    publishAdminEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminEventVersionRequest"];
            };
        };
        responses: {
            /** @description 공개된 행사 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventResponse"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    closeAdminEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminEventTransitionRequest"];
            };
        };
        responses: {
            /** @description 종료된 행사 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventResponse"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    cancelAdminEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminEventTransitionRequest"];
            };
        };
        responses: {
            /** @description 행사 취소 결과 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventCancelResponse"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    getAdminEventParticipants: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
                paymentStatus?: components["schemas"]["PaymentStatus"];
            };
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 행사 참가자 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventParticipantPage"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getAdminDuesPayments: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
                paymentStatus?: components["schemas"]["PaymentStatus"];
            };
            header?: never;
            path: {
                duesRoundId: components["parameters"]["DuesRoundId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회비 납부 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDuesPaymentPage"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getAdminDuesRounds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회비 차수 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDuesRoundResponse"][];
                };
            };
        };
    };
    createAdminDuesRound: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminDuesRoundRequest"];
            };
        };
        responses: {
            /** @description 생성된 회비 차수 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDuesRoundResponse"];
                };
            };
        };
    };
    deleteAdminDuesRound: {
        parameters: {
            query: {
                version: number;
            };
            header?: never;
            path: {
                duesRoundId: components["parameters"]["DuesRoundId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAdminDuesRound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                duesRoundId: components["parameters"]["DuesRoundId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminDuesRoundRequest"];
            };
        };
        responses: {
            /** @description 수정된 회비 차수 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDuesRoundResponse"];
                };
            };
        };
    };
    publishAdminDuesRound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                duesRoundId: components["parameters"]["DuesRoundId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminEventVersionRequest"];
            };
        };
        responses: {
            /** @description 공개 결과 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDuesPublishResponse"];
                };
            };
        };
    };
    confirmAdminPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: components["parameters"]["PaymentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminPaymentReviewRequest"];
            };
        };
        responses: {
            /** @description 승인된 납부 상태 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPaymentReviewResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    rejectAdminPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: components["parameters"]["PaymentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminPaymentReviewRequest"];
            };
        };
        responses: {
            /** @description 반려된 납부 상태 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPaymentReviewResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getAdminRefunds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 환불 대기 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPaymentRow"][];
                };
            };
        };
    };
    completeAdminRefund: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: components["parameters"]["PaymentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminPaymentReviewRequest"];
            };
        };
        responses: {
            /** @description 환불 완료 상태 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPaymentReviewResponse"];
                };
            };
        };
    };
    getAdminMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회원 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMemberResponse"][];
                };
            };
        };
    };
    approveAdminMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: components["parameters"]["MemberId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminMemberActionRequest"];
            };
        };
        responses: {
            /** @description 승인된 회원 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMemberResponse"];
                };
            };
        };
    };
    suspendAdminMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: components["parameters"]["MemberId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminMemberActionRequest"];
            };
        };
        responses: {
            /** @description 정지된 회원 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMemberResponse"];
                };
            };
        };
    };
    changeAdminMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: components["parameters"]["MemberId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminMemberRoleRequest"];
            };
        };
        responses: {
            /** @description 역할이 변경된 회원 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMemberResponse"];
                };
            };
        };
    };
    getAdminPaymentSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 송금정보 버전 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentSettingResponse"][];
                };
            };
        };
    };
    createAdminPaymentSetting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentSettingRequest"];
            };
        };
        responses: {
            /** @description 활성화된 송금정보 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentSettingResponse"];
                };
            };
        };
    };
    getActiveAdminPaymentSetting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 현재 활성 송금정보 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentSettingResponse"];
                };
            };
        };
    };
}
