/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 현재 사용자 조회 */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 최초 온보딩 완료 */
        patch: operations["completeOnboarding"];
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 내 프로필 수정 */
        patch: operations["updateMyProfile"];
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 게시 행사 목록 조회 */
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 행사 상세 조회 */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/participation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 행사 참가 신청 */
        post: operations["joinEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/participation/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 행사 참가 취소 */
        post: operations["cancelEventParticipation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/payment-obligations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 납부 항목 목록 */
        get: operations["getMyPaymentObligations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment-obligations/{paymentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 납부 상세 조회 */
        get: operations["getPaymentObligation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment-obligations/{paymentId}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 송금 완료 신고 */
        post: operations["reportPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 운영진 대시보드 조회 */
        get: operations["getAdminDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/events/{eventId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 행사별 참가자와 참가비 납부 현황 조회 */
        get: operations["getAdminEventParticipants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dues-rounds/{duesRoundId}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 회비 차수별 부원 납부 현황 조회 */
        get: operations["getAdminDuesPayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payment-obligations/{paymentId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 송금 신고 승인 */
        post: operations["confirmAdminPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payment-obligations/{paymentId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 송금 신고 반려 */
        post: operations["rejectAdminPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        MemberPart: "PLAN" | "DESIGN" | "PE_WEB" | "PE_MOBILE";
        /** @enum {string} */
        MemberRole: "MEMBER" | "STAFF" | "ADMIN";
        /** @enum {string} */
        MemberStatus: "PENDING" | "ACTIVE" | "SUSPENDED" | "WITHDRAWN";
        /** @enum {string} */
        EventStatus: "DRAFT" | "PUBLISHED" | "CLOSED" | "CANCELED";
        /** @enum {string} */
        ParticipationStatus: "JOINED" | "CANCELED";
        /** @enum {string} */
        PaymentType: "EVENT_FEE" | "MEMBERSHIP_DUE";
        /** @enum {string} */
        PaymentStatus: "NOT_REQUIRED" | "UNPAID" | "REPORTED" | "CONFIRMED" | "REJECTED" | "VOID" | "REFUND_PENDING" | "REFUNDED";
        /** @enum {string} */
        PaymentMethod: "BANK_TRANSFER" | "KAKAO_PAY_CODE";
        MeResponse: {
            /** Format: int64 */
            id: number;
            kakaoProfileName: string;
            name?: string;
            part?: components["schemas"]["MemberPart"];
            displayNickname?: string;
            role: components["schemas"]["MemberRole"];
            status: components["schemas"]["MemberStatus"];
            onboardingCompleted: boolean;
            /** Format: date-time */
            approvedAt?: string;
        };
        OnboardingRequest: {
            name: string;
            part: components["schemas"]["MemberPart"];
        };
        EventListItem: {
            /** Format: int64 */
            id: number;
            title: string;
            summary?: string;
            location?: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt?: string;
            /** Format: date-time */
            registrationDeadline: string;
            capacity?: number;
            joinedCount: number;
            /** Format: int64 */
            feeAmount: number;
            status: components["schemas"]["EventStatus"];
            myParticipationStatus?: components["schemas"]["ParticipationStatus"];
            myPaymentStatus?: components["schemas"]["PaymentStatus"];
        };
        EventPage: {
            items: components["schemas"]["EventListItem"][];
            page: number;
            size: number;
            totalElements: number;
            totalPages: number;
        };
        ParticipationSummary: {
            /** Format: int64 */
            id: number;
            status: components["schemas"]["ParticipationStatus"];
            /** Format: date-time */
            joinedAt: string;
            /** Format: date-time */
            canceledAt?: string;
            /** Format: int64 */
            version: number;
        };
        PaymentSummary: {
            /** Format: int64 */
            id: number;
            type: components["schemas"]["PaymentType"];
            /** Format: int64 */
            amount: number;
            status: components["schemas"]["PaymentStatus"];
            /** Format: date-time */
            dueAt?: string;
            source: components["schemas"]["PaymentSource"];
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
        };
        PaymentSource: {
            /** @enum {string} */
            type: "EVENT" | "DUES_ROUND";
            /** Format: int64 */
            id: number;
            title: string;
            /** Format: date-time */
            dueAt?: string;
        };
        EventDetail: components["schemas"]["EventListItem"] & {
            description: string;
            allowLateCancellation: boolean;
            canJoin: boolean;
            canCancel: boolean;
            myParticipation?: components["schemas"]["ParticipationSummary"];
            myPayment?: components["schemas"]["PaymentSummary"];
        };
        JoinEventResponse: {
            participation: components["schemas"]["ParticipationSummary"];
            payment: components["schemas"]["PaymentSummary"];
        };
        CancelParticipationRequest: {
            /** Format: int64 */
            version: number;
            reason?: string;
        };
        CancelParticipationResponse: {
            participationStatus: components["schemas"]["ParticipationStatus"];
            paymentStatus: components["schemas"]["PaymentStatus"];
            refundRequired: boolean;
        };
        PaymentPage: {
            items: components["schemas"]["PaymentSummary"][];
            page: number;
            size: number;
            totalElements: number;
            totalPages: number;
        };
        PaymentDestination: {
            bankName: string;
            accountNumber: string;
            accountHolder: string;
            /** Format: uri */
            kakaoPayReceiveUrl?: string;
        };
        PaymentReport: {
            /** Format: int64 */
            id: number;
            method: components["schemas"]["PaymentMethod"];
            senderName: string;
            /** Format: date-time */
            transferredAt?: string;
            note?: string;
            /** Format: date-time */
            reportedAt: string;
        };
        PaymentStatusHistory: {
            fromStatus?: components["schemas"]["PaymentStatus"];
            toStatus: components["schemas"]["PaymentStatus"];
            reason?: string;
            /** Format: date-time */
            changedAt: string;
        };
        PaymentDetail: components["schemas"]["PaymentSummary"] & {
            paymentDestination?: components["schemas"]["PaymentDestination"];
            latestReport?: components["schemas"]["PaymentReport"];
            statusHistory: components["schemas"]["PaymentStatusHistory"][];
        };
        PaymentReportRequest: {
            method: components["schemas"]["PaymentMethod"];
            senderName: string;
            /** Format: date-time */
            transferredAt?: string;
            note?: string;
            /** @constant */
            transferConfirmed: true;
            /** Format: int64 */
            version: number;
        };
        PaymentReportResponse: {
            report: components["schemas"]["PaymentReport"];
            paymentStatus: components["schemas"]["PaymentStatus"];
            /** Format: int64 */
            version: number;
        };
        AdminDashboardResponse: {
            memberCount: number;
            pendingMemberCount: number;
            upcomingEventCount: number;
            unpaidCount: number;
            reportedCount: number;
            /** Format: int64 */
            expectedAmount: number;
            /** Format: int64 */
            confirmedAmount: number;
            /** Format: double */
            collectionRate: number;
            upcomingEvents: components["schemas"]["AdminEventSummary"][];
            activeDuesRounds: components["schemas"]["AdminDuesRoundSummary"][];
            recentReports: components["schemas"]["AdminPaymentRow"][];
        };
        AdminEventSummary: {
            /** Format: int64 */
            id: number;
            title: string;
            /** Format: date-time */
            startsAt: string;
            capacity?: number;
            joinedCount: number;
            /** Format: int64 */
            feeAmount: number;
            unpaidCount: number;
            reportedCount: number;
            confirmedCount: number;
        };
        AdminDuesRoundSummary: {
            /** Format: int64 */
            id: number;
            title: string;
            /** Format: int64 */
            amount: number;
            /** Format: date-time */
            dueAt: string;
            targetCount: number;
            unpaidCount: number;
            reportedCount: number;
            confirmedCount: number;
            /** Format: int64 */
            confirmedAmount: number;
        };
        AdminPaymentRow: {
            /** Format: int64 */
            paymentId: number;
            /** Format: int64 */
            memberId: number;
            nickname: string;
            name: string;
            part: components["schemas"]["MemberPart"];
            /** Format: int64 */
            amount: number;
            status: components["schemas"]["PaymentStatus"];
            /** Format: date-time */
            dueAt: string;
            latestReport?: components["schemas"]["PaymentReport"];
            /** Format: int64 */
            version: number;
        };
        AdminEventParticipant: {
            /** Format: int64 */
            participationId: number;
            /** Format: int64 */
            memberId: number;
            nickname: string;
            name: string;
            part: components["schemas"]["MemberPart"];
            /** Format: date-time */
            joinedAt: string;
            /** Format: int64 */
            paymentId?: number;
            /** Format: int64 */
            amount: number;
            paymentStatus: components["schemas"]["PaymentStatus"];
            latestReport?: components["schemas"]["PaymentReport"];
            /** Format: int64 */
            version: number;
        };
        AdminEventParticipantPage: {
            event: components["schemas"]["AdminEventSummary"];
            items: components["schemas"]["AdminEventParticipant"][];
            page: number;
            size: number;
            totalElements: number;
            totalPages: number;
        };
        AdminDuesPaymentPage: {
            duesRound: components["schemas"]["AdminDuesRoundSummary"];
            items: components["schemas"]["AdminPaymentRow"][];
            page: number;
            size: number;
            totalElements: number;
            totalPages: number;
        };
        AdminPaymentReviewRequest: {
            /** Format: int64 */
            version: number;
            note?: string;
        };
        AdminPaymentReviewResponse: {
            /** Format: int64 */
            paymentId: number;
            status: components["schemas"]["PaymentStatus"];
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            reviewedAt: string;
        };
        Problem: {
            type?: string;
            title: string;
            status: number;
            code: string;
            detail: string;
            instance?: string;
            /** Format: date-time */
            timestamp: string;
            fieldErrors?: {
                field: string;
                reason: string;
            }[];
        };
    };
    responses: {
        /** @description 잘못된 요청 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 로그인 필요 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 접근 권한 없음 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 리소스 없음 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 현재 상태와 요청 충돌 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        EventId: number;
        PaymentId: number;
        DuesRoundId: number;
        Page: number;
        Size: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 현재 사용자 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    completeOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingRequest"];
            };
        };
        responses: {
            /** @description 온보딩 완료 사용자 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingRequest"];
            };
        };
        responses: {
            /** @description 수정된 사용자 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getEvents: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
                participating?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 행사 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 행사 상세 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    joinEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 참가 신청 결과 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinEventResponse"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    cancelEventParticipation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelParticipationRequest"];
            };
        };
        responses: {
            /** @description 참가 취소 결과 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelParticipationResponse"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    getMyPaymentObligations: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
                status?: components["schemas"]["PaymentStatus"][];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 납부 항목 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentPage"];
                };
            };
        };
    };
    getPaymentObligation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: components["parameters"]["PaymentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 납부 상세 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    reportPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: components["parameters"]["PaymentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentReportRequest"];
            };
        };
        responses: {
            /** @description 접수된 송금 신고 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentReportResponse"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    getAdminDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 운영 현황 요약 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDashboardResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getAdminEventParticipants: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
                paymentStatus?: components["schemas"]["PaymentStatus"];
            };
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 행사 참가자 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventParticipantPage"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getAdminDuesPayments: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
                paymentStatus?: components["schemas"]["PaymentStatus"];
            };
            header?: never;
            path: {
                duesRoundId: components["parameters"]["DuesRoundId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회비 납부 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDuesPaymentPage"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    confirmAdminPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: components["parameters"]["PaymentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminPaymentReviewRequest"];
            };
        };
        responses: {
            /** @description 승인된 납부 상태 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPaymentReviewResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    rejectAdminPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: components["parameters"]["PaymentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminPaymentReviewRequest"];
            };
        };
        responses: {
            /** @description 반려된 납부 상태 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPaymentReviewResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
}
