create table members (
    id bigint generated by default as identity primary key,
    kakao_id varchar(100) not null unique,
    kakao_profile_name varchar(100) not null,
    name varchar(50),
    part varchar(30),
    role varchar(20) not null,
    status varchar(20) not null,
    onboarding_completed boolean not null default false,
    approved_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version bigint not null default 0
);

create table club_events (
    id bigint generated by default as identity primary key,
    title varchar(200) not null,
    summary varchar(500),
    description text not null,
    location varchar(200),
    starts_at timestamp with time zone not null,
    ends_at timestamp with time zone,
    registration_deadline timestamp with time zone not null,
    capacity integer,
    fee_amount bigint not null,
    status varchar(20) not null,
    allow_late_cancellation boolean not null default false,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version bigint not null default 0,
    constraint ck_event_fee_non_negative check (fee_amount >= 0),
    constraint ck_event_capacity_positive check (capacity is null or capacity > 0)
);

create table participations (
    id bigint generated by default as identity primary key,
    event_id bigint not null references club_events(id),
    member_id bigint not null references members(id),
    status varchar(20) not null,
    joined_at timestamp with time zone not null,
    canceled_at timestamp with time zone,
    version bigint not null default 0,
    constraint uk_participation_event_member unique (event_id, member_id)
);

create table dues_rounds (
    id bigint generated by default as identity primary key,
    title varchar(200) not null,
    amount bigint not null,
    due_at timestamp with time zone not null,
    status varchar(20) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version bigint not null default 0,
    constraint ck_dues_amount_non_negative check (amount >= 0)
);

create table payment_obligations (
    id bigint generated by default as identity primary key,
    member_id bigint not null references members(id),
    type varchar(30) not null,
    amount bigint not null,
    status varchar(30) not null,
    source_type varchar(30) not null,
    source_id bigint not null,
    source_title varchar(200) not null,
    due_at timestamp with time zone,
    bank_name varchar(100),
    account_number varchar(100),
    account_holder varchar(100),
    kakao_pay_receive_url varchar(500),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version bigint not null default 0,
    constraint ck_payment_amount_non_negative check (amount >= 0),
    constraint uk_payment_member_source unique (member_id, source_type, source_id)
);

create table payment_reports (
    id bigint generated by default as identity primary key,
    payment_obligation_id bigint not null references payment_obligations(id),
    method varchar(30) not null,
    sender_name varchar(100) not null,
    transferred_at timestamp with time zone,
    note varchar(500),
    reported_at timestamp with time zone not null
);

create table payment_status_history (
    id bigint generated by default as identity primary key,
    payment_obligation_id bigint not null references payment_obligations(id),
    from_status varchar(30),
    to_status varchar(30) not null,
    reason varchar(500),
    changed_at timestamp with time zone not null
);

create index idx_events_status_starts_at on club_events(status, starts_at);
create index idx_participations_event_status on participations(event_id, status);
create index idx_payment_member_status on payment_obligations(member_id, status);
create index idx_payment_source on payment_obligations(source_type, source_id);
create index idx_payment_reports_obligation on payment_reports(payment_obligation_id, reported_at);
