create table payment_settings (
    id bigint generated by default as identity primary key,
    bank_name varchar(100) not null,
    account_number varchar(100) not null,
    account_holder varchar(100) not null,
    kakao_pay_receive_url varchar(500),
    active boolean not null,
    created_by bigint not null references members(id),
    created_at timestamp with time zone not null
);
