create table notifications (
    id bigint generated by default as identity primary key,
    member_id bigint not null references members(id),
    title varchar(200) not null,
    body varchar(500) not null,
    link_url varchar(500),
    read_at timestamp with time zone,
    created_at timestamp with time zone not null
);
create index idx_notifications_member_created on notifications(member_id, created_at desc);
