import { expect, test } from '@playwright/test'

test('모바일에서 홈·행사·납부를 이동하고 필터·이전 주소를 유지한다', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/home')
  await expect(page.getByRole('heading', { name: /안녕하세요/ })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('home-mobile.png'), fullPage: true })
  const menu = page.getByRole('navigation', { name: '주요 메뉴' })
  await menu.getByRole('link', { name: '행사', exact: true }).click()
  await expect(page).toHaveURL(/\/events$/)
  await expect(page.getByRole('heading', { name: '행사', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: /안녕하세요/ })).toHaveCount(0)
  await page.getByLabel('참여 상태').selectOption('JOINED')
  await expect(page).toHaveURL(/participation=JOINED/)
  await page.screenshot({ path: testInfo.outputPath('events-mobile.png'), fullPage: true })
  await page.locator('a[href="/events/42"]').click()
  await expect(menu.getByRole('link', { name: '행사', exact: true })).toHaveAttribute('aria-current', 'page')
  await page.goBack()
  await expect(page.getByLabel('참여 상태')).toHaveValue('JOINED')
  await menu.getByRole('link', { name: '납부', exact: true }).click()
  await expect(page.getByRole('heading', { name: '납부 내역', exact: true })).toBeVisible()
  await page.getByLabel('납부 구분').selectOption('MEMBERSHIP_DUE')
  await page.getByLabel('납부 상태').selectOption('REPORTED')
  await page.reload()
  await expect(page.getByLabel('납부 구분')).toHaveValue('MEMBERSHIP_DUE')
  await expect(page.getByLabel('납부 상태')).toHaveValue('REPORTED')
  await page.screenshot({ path: testInfo.outputPath('payments-mobile.png'), fullPage: true })
  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
  await page.goto('/home#events')
  await expect(page).toHaveURL(/\/events$/)
  await page.goto('/home#payments')
  await expect(page).toHaveURL(/\/payments$/)
  await page.setViewportSize({ width: 1280, height: 900 })
  await expect(menu.getByRole('link', { name: '납부', exact: true })).toHaveAttribute('aria-current', 'page')
  await page.screenshot({ path: testInfo.outputPath('payments-desktop.png'), fullPage: true })
})

test('실제 Spring API로 송금 신고·승인·참가 취소와 행사 생성을 처리한다', async ({ page }) => {
  await page.goto('/home')
  await expect(page.getByText('PE(Web) 김총무')).toBeVisible()
  await expect(page.locator('a[href="/events/42"]')).toBeVisible()

  await page.goto('/payments/311')
  await expect(page.getByLabel('송금자명')).toHaveValue('김총무')
  await page.getByLabel('실제로 송금을 완료했습니다.').check()
  await page.getByRole('button', { name: '송금했어요' }).click()
  await expect(page.getByRole('heading', { name: '송금 신고가 접수됐어요.' })).toBeVisible()

  await page.goto('/admin')
  await page.getByRole('link', { name: '확인하러 가기 →' }).click()
  await expect(page).toHaveURL(/\/admin\/payment-reports$/)
  const reportRow = page.getByRole('row').filter({ has: page.getByRole('link', { name: /행사비 · 2026 가을 해커톤/ }) })
    .filter({ has: page.getByRole('button', { name: '김총무 납부 승인' }) })
  await reportRow.getByRole('button', { name: '김총무 납부 승인' }).click()
  await expect(reportRow).toHaveCount(0)
  await page.goto('/admin/events/42/participants')
  await expect(page.getByRole('row', { name: /김총무/ })).toContainText('납부 완료')

  await page.goto('/events/42')
  await page.getByRole('button', { name: '참가 취소' }).click()
  await page.getByRole('button', { name: '참가 취소 확정' }).click()
  await expect(page.getByRole('heading', { name: '참가 신청이 취소됐어요.' })).toBeVisible()
  await expect(page.getByText(/환불 대기 상태/)).toBeVisible()

  await page.goto('/admin/events')
  await page.getByRole('textbox', { name: '행사명' }).fill('E2E 네트워킹 행사')
  await page.getByRole('textbox', { name: '상세 내용' }).fill('실제 API로 생성하는 행사입니다.')
  await page.getByRole('button', { name: '초안 저장' }).click()
  await expect(page.getByText('행사 초안을 저장했습니다.')).toBeVisible()
  await page.getByRole('button', { name: '행사 공개' }).click()
  await expect(page.getByText('동아리원에게 행사를 공개했습니다.')).toBeVisible()
  await expect(page.getByText('공개').last()).toBeVisible()
})

test('Markdown 초안을 저장·수정·공개하고 모바일 행사 안내에서 확인한다', async ({ page }, testInfo) => {
  const markdown = [
    '## 모임 준비 안내', '', '**노트북**을 준비해 주세요.', '충전기도 필요합니다.', '',
    '- 학생회관에서 만나요.', '',
    '| 시간 | 내용 | 장소 | 준비물 |', '| --- | --- | --- | --- |', '| 18:00 | 개발 모임 | 학생회관 | 노트북 |', '',
    '[안내 사이트](https://example.com)', '',
    '```text', 'a'.repeat(150), '```', '',
    '<script>window.markdownExecuted = true</script>', '',
    '[위험 링크](javascript:alert%281%29)', '', '![추적](https://example.com/tracker.png)',
  ].join('\n')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/admin/events')
  await page.getByRole('textbox', { name: '행사명' }).fill('Markdown E2E 행사')
  await page.getByRole('textbox', { name: '상세 내용' }).fill(markdown)
  await page.getByRole('button', { name: '미리보기' }).click()
  await expect(page.getByRole('heading', { name: '모임 준비 안내' })).toBeVisible()
  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: testInfo.outputPath('markdown-admin-mobile.png'), fullPage: true })
  const created = page.waitForResponse((response) => response.url().endsWith('/api/v1/admin/events') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '초안 저장' }).click()
  const response = await created
  expect(response.ok()).toBe(true)
  const event = await response.json()
  expect(event.description).toBe(markdown)
  await page.reload()
  await page.getByRole('button').filter({ has: page.getByText('Markdown E2E 행사', { exact: true }) }).click()
  await expect(page.getByRole('textbox', { name: '상세 내용' })).toHaveValue(markdown)
  const updatedMarkdown = markdown + '\n\n**수정한 공지**'
  await page.getByRole('textbox', { name: '상세 내용' }).fill(updatedMarkdown)
  const updated = page.waitForResponse((response) => response.url().endsWith(`/api/v1/admin/events/${event.id}`) && response.request().method() === 'PATCH')
  await page.getByRole('button', { name: '초안 저장' }).click()
  expect((await updated).ok()).toBe(true)
  await page.getByRole('button', { name: '행사 공개' }).click()
  await expect(page.getByText('동아리원에게 행사를 공개했습니다.')).toBeVisible()
  await page.goto(`/events/${event.id}`)
  await page.reload()
  await expect(page.getByRole('heading', { name: '모임 준비 안내' })).toBeVisible()
  await expect(page.locator('.markdown-content strong').filter({ hasText: '수정한 공지' })).toBeVisible()
  await expect(page.getByRole('table')).toContainText('학생회관')
  await expect(page.getByRole('link', { name: '안내 사이트' })).toHaveAttribute('rel', 'noopener noreferrer')
  await expect(page.getByRole('link', { name: '위험 링크' })).toHaveCount(0)
  await expect(page.locator('.markdown-content script, .markdown-content img')).toHaveCount(0)
  for (const width of [390, 320, 1280]) {
    await page.setViewportSize({ width, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`markdown-member-${width}.png`), fullPage: true })
  }
})

test('로컬 회원가입·온보딩 후 모바일 마이페이지에서 로그아웃하고 재로그인한다', async ({ page }, testInfo) => {
  await page.goto('/login')
  await page.getByRole('button', { name: '회원가입 화면 열기' }).click()
  await page.getByLabel('아이디').fill('e2e.local.member')
  await page.getByLabel('비밀번호').fill('clubpass123!')
  await page.getByLabel('전화번호').fill('010-8765-4321')
  await page.getByRole('button', { name: '회원가입', exact: true }).click()

  await expect(page.getByRole('status')).toContainText('회원가입이 완료됐어요')
  await page.getByLabel('비밀번호').fill('clubpass123!')
  await page.getByRole('button', { name: '아이디로 로그인' }).click()

  await expect(page.getByRole('heading', { name: /어떤 파트에서/ })).toBeVisible()
  await page.getByLabel(/Plan/).check()
  await page.getByLabel('이름').fill('로컬회원')
  await page.getByRole('button', { name: '이 이름으로 시작하기' }).click()
  await expect(page.getByRole('heading', { name: /가입 신청이/ })).toBeVisible()
  await expect(page.getByText('Plan 로컬회원')).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('link', { name: '내 정보 확인하기' }).click()
  await expect(page.getByRole('heading', { name: '마이페이지' })).toBeVisible()
  await expect(page.getByText('010-8765-4321')).toBeVisible()
  await expect(page.getByRole('link', { name: '마이', exact: true })).toHaveAttribute('aria-current', 'page')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('mypage-mobile.png'), fullPage: true })
  await page.setViewportSize({ width: 320, height: 740 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: '로그아웃', exact: true }).click()
  await expect(page).toHaveURL(/\/login$/)
  await page.getByLabel('아이디').fill('e2e.local.member')
  await page.getByLabel('비밀번호').fill('clubpass123!')
  await page.getByRole('button', { name: '아이디로 로그인' }).click()
  await expect(page.getByRole('heading', { name: /가입 신청이/ })).toBeVisible()
  await expect(page.getByText('Plan 로컬회원')).toBeVisible()
})
